MonoControl:
  Options: --jit
Coprocessor:
  # Should the ESP32 automatically attempt to connect to an access point at startup?
  # If set to true, wifi.config.yaml credentials must be stored in the device.
  AutomaticallyStartNetwork: true
  # Should the ESP32 automatically reconnect to the configured access point?
  AutomaticallyReconnect: true
  # Maximum number of retry attempts for connections etc. before an error code is returned.
  MaximumRetryCount: 2
Network:
  # Automatically attempt to get the time at startup?
  GetNetworkTimeAtStartup: true
  # Time synchronization period in seconds.
  NtpRefreshPeriodSeconds: 600
  # Name of the NTP servers.
  NtpServers:
    - 0.pool.ntp.org
    - 1.pool.ntp.org
    - 2.pool.ntp.org
    - 3.pool.ntp.org