# Uncomment additional options as needed.
# To learn more about these config options, including custom application configuration settings, check out the Application Settings Configuration documentation.
# http://developer.wildernesslabs.co/Meadow/Meadow.OS/Configuration/Application_Settings_Configuration/

# Logging configuration.
Logging:

    # Adjust the level of logging detail.
    LogLevel:
    
        # Trace, Debug, Information, Warning, or Error
        Default: Trace

# Meadow.Cloud configuration.
MeadowCloud:
    
    # Enable Logging, Events, Command + Control
    Enabled: true

    # Enable Over-the-air Updates
#    EnableUpdates: true

    # Enable Health Metrics
#    EnableHealthMetrics: true

    # How often to send metrics to Meadow.Cloud
#    HealthMetricsIntervalMinutes: 5