# Uncomment additional options as needed.
# To learn more about these config options, including custom application configuration settings, check out the Application Settings Configuration documentation.
# http://developer.wildernesslabs.co/Meadow/Meadow.OS/Configuration/Application_Settings_Configuration/

Logging:
  LogLevel:
    Default: Trace
Lifecycle:
  ResetOnAppFailure: false
Update:
  Enabled: true
  UpdateServer: mqtt-staging.meadowcloud.co
MeadowCloud:
  Hostname: https://staging.meadowcloud.dev
  DataHostname: https://collector-staging.meadowcloud.dev
HealthMetrics:
  Enabled: true
  Interval: 5